# Generated by Django 3.1.7 on 2021-03-14 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(db_index=True, max_length=144, unique=True, verbose_name='Location')),
                ('street', models.CharField(max_length=144, verbose_name='Street')),
                ('street_no', models.CharField(max_length=10, verbose_name='Street Number')),
                ('postcode', models.CharField(max_length=9, verbose_name='Postcode')),
                ('additional', models.CharField(max_length=144, verbose_name='Additional')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.department', verbose_name='Department'),
        ),
    ]
