# Generated by Django 3.1.7 on 2021-03-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210314_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.AddField(
            model_name='department',
            name='city',
            field=models.CharField(default='Any', max_length=144, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_identifier',
            field=models.CharField(db_index=True, default='Any', max_length=144, unique=True, verbose_name='Department Identifier'),
            preserve_default=False,
        ),
    ]
