# Generated by Django 3.1.7 on 2021-03-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20210314_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=144, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=144, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('street', models.CharField(max_length=144, verbose_name='Street')),
                ('street_no', models.CharField(max_length=10, verbose_name='Street Number')),
                ('city', models.CharField(max_length=144, verbose_name='City')),
                ('postcode', models.CharField(max_length=9, verbose_name='Postcode')),
                ('additional', models.CharField(max_length=144, verbose_name='Additional')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Creation Timestamp')),
                ('planed_entry', models.DateTimeField(verbose_name='Planned Entry')),
                ('entry', models.DateTimeField(blank=True, null=True, verbose_name='Entry')),
                ('outgoing', models.DateTimeField(blank=True, null=True, verbose_name='Exit')),
                ('was_present', models.BooleanField(default=False, editable=False, verbose_name='Was Present')),
                ('key', models.PositiveIntegerField(db_index=True, verbose_name='Key')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='accounts.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ('-creation_timestamp',),
                'unique_together': {('key', 'department')},
            },
        ),
    ]
